name: mini_rpg_flutter
description: "Project For Game DB Modeling"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  window_manager: ^0.5.0
  dio: ^5.8.0+1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  fonts:
    - family: pixel
      fonts:
        - asset: assets/fonts/DungGeunMo.ttf
